// This file contains all the VndType used in the API
export const VndType = {
  APPLICATION_USER: "application/vnd.user.v1+json",
  APPLICATION_USERS: "application/vnd.users.v1+json",
  APPLICATION_USER_PASSWORD: "application/vnd.userPassword.v1+json",
  APPLICATION_USER_RESET_PASSWORD: "application/vnd.userResetPassword.v1+json",
  APPLICATION_USER_VERIFY: "application/vnd.userVerify.v1+json",
  APPLICATION_USER_PROVIDER: "application/vnd.userProvider.v1+json",
  APPLICATION_USER_OCCUPIED_DATES: "application/vnd.userOccupiedDates.v1+json",
  APPLICATION_OFFERINGS: "application/vnd.services.v1+json",
  APPLICATION_OFFERING: "application/vnd.service.v1+json",
  APPLICATION_OFFERING_CATEGORIES: "application/vnd.serviceCategories.v1+json",
  APPLICATION_OFFERING_PRICE_TYPES: "application/vnd.servicePriceTypes.v1+json",
  APPLICATION_DISTRICTS: "application/vnd.districts.v1+json",
  APPLICATION_LIKE: "application/vnd.like.v1+json",
  APPLICATION_EVENT: "application/vnd.event.v1+json",
  APPLICATION_EVENTS: "application/vnd.events.v1+json",
  APPLICATION_REVIEW: "application/vnd.review.v1+json",
  APPLICATION_REVIEWS: "application/vnd.reviews.v1+json",
  APPLICATION_GUEST: "application/vnd.guest.v1+json",
  APPLICATION_GUEST_STATUS: "application/vnd.guestStatus.v1+json",
  APPLICATION_GUESTS: "application/vnd.guests.v1+json",
  APPLICATION_RELATION: "application/vnd.relation.v1+json",
  APPLICATION_RELATION_STATUS: "application/vnd.relationStatus.v1+json",
  APPLICATION_RELATIONS: "application/vnd.relations.v1+json",
  APPLICATION_RELATION_READ_STATUS: "application/vnd.relationReadStatus.v1+json",
  APPLICATION_MESSAGE: "application/vnd.message.v1+json",
  APPLICATION_MESSAGES: "application/vnd.messages.v1+json",
};
